### ISSUE TITLE
Enforce naming conventions?

### ISSUE THREAD

**Issue by ltratt** [softdevteam/softdevbib#12]
Currently we nearly always name things "firstauthorYYpapertitle" e.g. "blogs17blah". But a recent PR slipped in "intel2017pstate" instead of "intel17pstate" (my bad for not noticing it). We could enforce this naming scheme, I think, with prebib?

**Comment by ltratt** [comment]
I've done a PR with a fix for that entry (and the paper now relies on it!). We can create false examples easily enough ;)

**Comment by ltratt** [comment]
@vext01 should we close this or address it?

**Comment by vext01** [comment]
Should be easy to fix in prebib. I can have a look some time this week.

**Comment by ltratt** [comment]
Excellent!

**Comment by ltratt** [comment]
@vext01 Should we close this?
