### ISSUE TITLE
Fix lint warnings and add travis config

### ISSUE THREAD

**Issue by ltratt** [softdevteam/softdevbib#3]
Currently `prebib` emits several linter warnings, which we've got in the habit of ignoring. We should fix these or explicitly add them as exceptional cases. Once that's done, we can then have prebib turn warnings into errors and add a travis switch so that PRs can't be merged unless the linter is happy.

**Comment by ltratt** [comment]
Is this still active?

**Comment by vext01** [comment]
I don't think so.

prebib doesn't make any warning on our current DB, and the travis config is in place.
