### ISSUE TITLE
Too many warnings about missing months

### ISSUE THREAD

**Issue by ltratt** [softdevteam/softdevbib#35]
`prebib` gives us 161 warnings for `softdev.bib` complaining that:

```
***warn: Entry 'cheatham69extensible' is missing a 'month' field
```

I think we should a) make this not be a warning (we're never going to fix 161 of them; and some of them are probably unfixable) b) maybe we could make warnings less visually obtrusive by just being `Warning: 'cheatham69extensible' is missing a 'month' field` or similar?

**Comment by ltratt** [comment]
Maybe this only happens if you specify `-x month`? But, even so, the warning isn't very helpful at this scale.

**Comment by vext01** [comment]
It's a tricky one.

I don't think changing the format of the error helps. My hypothesis is that no-one reads these messages unless they are fatal, which warnings are not (there's also a fatal error type in prebib).

Unfortunately we've let sloppy references into our database, and all we can do is either:
 * Fix them (which -- you are right -- is a lot of effort for little gain, but we could divide the work amongst the team).
 * Ignore them as people have been for some time it seems. This swamps other warnings I suppose.
 * Remove this warning.
 * Add a `-x month`

Neither solution is particularly nice IMHO. Sadly I think the first option (fixing them) would be the correct solution, although I don't know what to to if you couldn't find a date...

**Comment by ltratt** [comment]
Right, sometimes we won't be able to find a date, so in that sense it's not really clear that the warning is useful. We can't distinguish between "couldn't find a date" and "couldn't be bothered to find a date". I wouldn't mind doing a sweep through to try and fix those that are fixable, but my guess is that a significant proportion would still be missing them.

I'm also unsure if warnings should make `prebib` return a non-zero exit code (as they currently seem to).

**Comment by vext01** [comment]
> I'm also unsure if warnings should make prebib return a non-zero exit code (as they currently seem to)

Is that right? Wouldn't that  stop `make`? I'm sure I've used pre-bib for hamlet without crashes recently...

**Comment by ltratt** [comment]
Try it now...

**Comment by vext01** [comment]
If I `make clean` the hamlet proposal, then kill `bib.bib` and the whole `softdevbib` clone, then run `make` all is well.

But you were expecting it to fail? Or?

**Comment by ltratt** [comment]
Fixed in https://github.com/softdevteam/softdevbib/pull/36
